---
- name: Check if OpenSSH is installed
  ansible.builtin.stat:
    path: /etc/ssh/sshd_config
  register: sshd_config_exists

- name: Abort if sshd is not installed
  ansible.builtin.fail:
    msg: "OpenSSH server is not installed. Exiting."
  when: not sshd_config_exists.stat.exists

- name: Apply hardened SSH configuration
  ansible.builtin.template:
    src: sshd_config.j2
    dest: "{{ sshd_hardening_config_path }}"
    owner: root
    group: root
    mode: '0600'
  notify: restart sshd
