---
authors:
  - Daniel Schwitzgebel
namespace: schwitzd
name: collection
description: My personal Ansible collection
readme: README.md
repository: https://github.com/Schwitzd/me.ansible_collection
license_file: LICENSE
version: 1.6.0