[semantic_release]
version_variables = [
    "galaxy.yml:version:nf"
]

[tool.semantic_release]
branch = "main"
upload_to_pypi = false
upload_to_release = true

[tool.semantic_release.changelog]
exclude_commit_patterns = [
  "chore(?:\\([^)]*?\\))?: .+",
  "ci(?:\\([^)]*?\\))?: .+",
  "refactor(?:\\([^)]*?\\))?: .+",
  "style(?:\\([^)]*?\\))?: .+",
  "test(?:\\([^)]*?\\))?: .+",
  "build\\((?!deps\\): .+)",
  "Initial [Cc]ommit.*"
]